### PR TITLE
Update to support 8-16 bit integer formats.

### PR DESCRIPTION
**Pull request by adworacz**
Also add some minor documentation.

### CODE REVIEW

**Comment by dubhater** [comment]
Thanks!

**Comment by adworacz** [comment]
Sure thing! Thanks for merging so fast!

**Comment by dubhater** [comment]
I'm told that DFMDerainbowMC doesn't do anything in 16 bits. What do you think?

**Comment by adworacz** [comment]
I'd suspect it does, but because of the edge mask, it's only discernible on edges. I noticed the same thing with 8-bit to be fair - I couldn't see DFMMC doing anything at all, then I investigated the edgemask and discovered that it was only derainbowing where the Prewitt told it to. This differs significantly from the normal DFM behavior.

I was actually planning on PR to allow passing in masks, or disabling them completely. I've been unimpressed with the default edge masking behavior.

I'll put some screenshots together - I did some testing in 16-bit recently, so I know it does work.

**Comment by adworacz** [comment]
Sorry for the radio silence here, been traveling a fair amount.

I have the beginnings of mask control support added here: https://github.com/adworacz/vapoursynth-dfmderainbow/commit/d1a396c1340a4021b011a7ee855202b49a0be981

I have some screenshots from the results, but needless to say - disabling the default masking does produce a noticeable change when using DFMMC.

**Pull request merged**
